#include "mqtt_manager.h"
#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "mqtt_client.h"

// --- MQTT Broker Configuration ---
#define MQTT_BROKER_URI   "mqtts://192.168.1.16:8883"

// --- MQTT Client Configuration ---
#define MQTT_CLIENT_ID    "NodeMCUClient_TLS_01"
#define MQTT_USERNAME     "mqtt_user"
#define MQTT_PASSWORD     "interOP@123"

// --- MQTT Topics ---
const char* mqtt_publish_topic = "nodemcu/status";
const char* mqtt_subscribe_topic = "nodemcu/commands";

static const char *TAG = "MQTT_MANAGER";

static esp_mqtt_client_handle_t client;
static TaskHandle_t publisher_task_handle = NULL;

// These are the symbols for the embedded certificate files.
// They are generated by the build system via EMBED_TXTFILES in CMakeLists.txt
extern const uint8_t ca_crt_start[] asm("_binary_ca_crt_start");
extern const uint8_t ca_crt_end[]   asm("_binary_ca_crt_end");
extern const uint8_t client_crt_start[] asm("_binary_client_crt_start");
extern const uint8_t client_crt_end[]   asm("_binary_client_crt_end");
extern const uint8_t client_key_start[] asm("_binary_client_key_start");
extern const uint8_t client_key_end[]   asm("_binary_client_key_end");

static void mqtt_publisher_task(void *pvParameters)
{
    char message_buffer[100];
    while(1) {
        // Use snprintf for safer string formatting
        snprintf(message_buffer, sizeof(message_buffer), "Hello from ESP-IDF! Uptime: %lus", esp_log_timestamp() / 1000);
        ESP_LOGI(TAG, "Publishing message: %s", message_buffer);
        
        int msg_id = esp_mqtt_client_publish(client, mqtt_publish_topic, message_buffer, 0, 1, 0);
        if (msg_id != -1) {
            ESP_LOGI(TAG, "sent publish successful, msg_id=%d", msg_id);
        } else {
            ESP_LOGE(TAG, "failed to publish message");
        }

        vTaskDelay(5000 / portTICK_PERIOD_MS);
    }
}

static void mqtt_event_handler(void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data)
{
    ESP_LOGD(TAG, "Event dispatched from event loop base=%s, event_id=%ld", base, event_id);
    esp_mqtt_event_handle_t event = (esp_mqtt_event_handle_t)event_data;
    
    switch ((esp_mqtt_event_id_t)event_id) {
    case MQTT_EVENT_CONNECTED:
        ESP_LOGI(TAG, "MQTT_EVENT_CONNECTED");
        esp_mqtt_client_subscribe(client, mqtt_subscribe_topic, 0);
        ESP_LOGI(TAG, "Subscribed to: %s", mqtt_subscribe_topic);
        // Start the publisher task once connected if not already running
        if (publisher_task_handle == NULL) {
            xTaskCreate(&mqtt_publisher_task, "mqtt_publisher_task", 4096, NULL, 5, &publisher_task_handle);
        }
        break;
    case MQTT_EVENT_DISCONNECTED:
        ESP_LOGI(TAG, "MQTT_EVENT_DISCONNECTED");
        // Delete the publisher task if the client disconnects to avoid duplicates on reconnect
        if (publisher_task_handle != NULL) {
            vTaskDelete(publisher_task_handle);
            publisher_task_handle = NULL;
        }
        // NOTE: The MQTT client will automatically try to reconnect.
        break;
    case MQTT_EVENT_SUBSCRIBED:
        ESP_LOGI(TAG, "MQTT_EVENT_SUBSCRIBED, msg_id=%d", event->msg_id);
        break;
    case MQTT_EVENT_UNSUBSCRIBED:
        ESP_LOGI(TAG, "MQTT_EVENT_UNSUBSCRIBED, msg_id=%d", event->msg_id);
        break;
    case MQTT_EVENT_PUBLISHED:
        ESP_LOGI(TAG, "MQTT_EVENT_PUBLISHED, msg_id=%d", event->msg_id);
        break;
    case MQTT_EVENT_DATA:
        ESP_LOGI(TAG, "MQTT_EVENT_DATA");
        printf("TOPIC=%.*s\r\n", event->topic_len, event->topic);
        printf("DATA=%.*s\r\n", event->data_len, event->data);
        // Add your logic here to handle incoming commands
        break;
    case MQTT_EVENT_ERROR:
        ESP_LOGE(TAG, "MQTT_EVENT_ERROR");
        if (event->error_handle->error_type == MQTT_ERROR_TYPE_TCP_TRANSPORT) {
            ESP_LOGE(TAG, "Last error code reported from esp-tls: 0x%x", event->error_handle->esp_tls_last_esp_err);
            ESP_LOGE(TAG, "Last tls stack error number: 0x%x", event->error_handle->esp_tls_stack_err);
        } else if (event->error_handle->error_type == MQTT_ERROR_TYPE_CONNECTION_REFUSED) {
            ESP_LOGE(TAG, "Connection refused error: 0x%x", event->error_handle->connect_return_code);
        } else {
            ESP_LOGW(TAG, "Unknown error type: 0x%x", event->error_handle->error_type);
        }
        break;
    default:
        ESP_LOGI(TAG, "Other event id:%d", event->event_id);
        break;
    }
}

void mqtt_app_start(void)
{
    esp_mqtt_client_config_t mqtt_cfg = {};
    mqtt_cfg.broker.address.uri = MQTT_BROKER_URI;
    mqtt_cfg.broker.verification.certificate = (const char *)ca_crt_start;
    mqtt_cfg.credentials.client_id = MQTT_CLIENT_ID;
    mqtt_cfg.credentials.username = MQTT_USERNAME;
    mqtt_cfg.credentials.authentication.password = MQTT_PASSWORD;
    mqtt_cfg.credentials.authentication.certificate = (const char *)client_crt_start;
    mqtt_cfg.credentials.authentication.key = (const char *)client_key_start;

    client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_register_event(client, (esp_mqtt_event_id_t)ESP_EVENT_ANY_ID, mqtt_event_handler, NULL);
    esp_mqtt_client_start(client);
}