spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

flm:
  jwt:
    secret: ${FLM_JWT_SECRET}
  mqtt:
    broker-url: ${FLM_MQTT_BROKER_URL}
    username: ${FLM_MQTT_USERNAME}
    password: ${FLM_MQTT_PASSWORD}
    tls-enabled: ${FLM_MQTT_TLS_ENABLED:false}
    topic-filter: ${FLM_MQTT_TOPIC_FILTER:+/water/#}
