# Mosquitto — host-native / standalone with Dynamic Security

per_listener_settings false

listener 1883 0.0.0.0
protocol mqtt
allow_anonymous false

listener 8883 0.0.0.0
protocol mqtt
cafile ../certs/ca.crt
certfile ../certs/server.crt
keyfile ../certs/server.key
tls_version tlsv1.2
max_packet_size 2048
allow_anonymous false

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file ../config/dynamic-security.json

persistence true
persistence_location ../data/
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

max_connections 200
max_keepalive 120
